### ISSUE TITLE
Github Issue Template has wrong emoji

### ISSUE THREAD

**Issue by Jdecristi** [Jdecristi/chirp#31]
Github Issue Template has wrong emoji

## To Reproduce

1. Go to [chirp_issues](https://github.com/Jdecristi/chirp/issues)
2. Click on "New Issue"
3. See error Ghost Emoji 👻 next to "Feature request"

## Expected behavior
Ghost Emoji 👻 should be  Chirp Emoji 🐣

## Screenshots

<img width="1189" alt="Screenshot 2023-09-21 at 10 50 11 PM" src="https://github.com/Jdecristi/chirp/assets/89173284/9d9e0199-5360-4971-8228-3bccee81dacd">

**Comment by h4amin** [comment]
I'll take this issue
